BuilderCommon:
  BuilderClass: HnswRabitqStreamer
  BuildFile: /root/data/cohere/1m/cohere_train_vector_1m.norm.zvec.vecs
  DumpPath: ./false.tmp
  IndexPath: /root/data/cohere/1m/index/cohere.ip.rabitq.index

  ThreadCount: 16

  MetricName: InnerProduct

  DisableIdMap: true


BuilderParams: #各Builder方法的params参数
  proxima.hnsw_rabitq.general.dimension: !!int 768
  proxima.hnsw_rabitq.streamer.efconstruction: !!int 500
  proxima.hnsw_rabitq.streamer.use_id_map: !!bool false
  proxima.hnsw_rabitq.streamer.max_neighbor_count: !!int 15

RabitqConverterParams: #RaBitQ量化器参数
  proxima.rabitq.num_clusters: !!int 16
  proxima.rabitq.total_bits: !!int 7
