<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>org.zvec.examples</groupId>
  <artifactId>zvec-java-quickstart-jni</artifactId>
  <version>0.0.1-SNAPSHOT</version>
  <name>zvec-java-quickstart-jni</name>

  <properties>
    <maven.compiler.release>11</maven.compiler.release>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <zvec.version>0.0.1-SNAPSHOT</zvec.version>
  </properties>

  <dependencies>
    <dependency>
      <groupId>org.zvec</groupId>
      <artifactId>zvec-java-jni</artifactId>
      <version>${zvec.version}</version>
    </dependency>
  </dependencies>

  <build>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-compiler-plugin</artifactId>
        <version>3.14.0</version>
        <configuration>
          <release>${maven.compiler.release}</release>
        </configuration>
      </plugin>
      <plugin>
        <groupId>org.codehaus.mojo</groupId>
        <artifactId>exec-maven-plugin</artifactId>
        <version>3.5.0</version>
        <configuration>
          <mainClass>org.zvec.demo.QuickStartDemo</mainClass>
        </configuration>
      </plugin>
    </plugins>
  </build>
</project>
